
$version="3.2.13"


/*numu dis*/
energy(#dis_numu_sig)<>
include "./smr/dis_numu_sig.txt"
energy(#dis_nutau_bkg)<>
include "./smr/dis_nutau_bkg.txt"
energy(#dis_numubar_sig)<>
include "./smr/dis_numubar_sig.txt"
energy(#dis_nutaubar_bkg)<>
include "./smr/dis_nutaubar_bkg.txt"
energy(#dis_NC_bkg)<>
include "./smr/dis_NC_bkg.txt"
energy(#dis_aNC_bkg)<>
include "./smr/dis_aNC_bkg.txt"

/*nue app*/
energy(#app_nue_sig)<>
include "./smr/app_nue_sig.txt"
energy(#app_nue_bkg)<>
include "./smr/app_nue_bkg.txt"
energy(#app_numu_bkg)<>
include "./smr/app_numu_bkg.txt"
energy(#app_nutau_bkg)<>
include "./smr/app_nutau_bkg.txt"
energy(#app_nuebar_sig)<>
include "./smr/app_nuebar_sig.txt"
energy(#app_nuebar_bkg)<>
include "./smr/app_nuebar_bkg.txt"
energy(#app_numubar_bkg)<>
include "./smr/app_numubar_bkg.txt"
energy(#app_nutaubar_bkg)<>
include "./smr/app_nutaubar_bkg.txt"
energy(#app_NC_bkg)<>
include "./smr/app_NC_bkg.txt"
energy(#app_aNC_bkg)<>
include "./smr/app_aNC_bkg.txt"
