PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 1
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 2
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 3
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 4
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 5
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 6
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 7
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 8
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 9
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 10
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 11
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 12
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 13
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 14
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 15
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 16
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 17
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 18
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 19
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 20
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 21
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 22
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 23
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 24
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 25
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 26
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 27
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 28
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 29
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 30
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 31
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 32
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 33
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 34
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 35
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 36
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 37
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 38
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 39
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 40
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 41
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 42
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 43
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 44
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 45
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 46
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 47
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 48
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 49
PRISM_4Flavour_dChi2Scan --fcl fcl/PRISM/PRISMOscScan_Grid.fcl --binx 50
