bin:
g++ eventCount.cc Arguments.cc FileInfo.cc `root-config --cflags --libs` -oeventCount
mv eventCount $(SRT_PRIVATE_CONTEXT)/bin/$(SRT_SUBDIR)/

clean:
rm -f $(SRT_PRIVATE_CONTEXT)/bin/$(SRT_SUBDIR)/eventCount

lib:

codegen:

include:

depend:

libobjects:
