sigdcp: sigdcp.c ../customchis/customChis.o
	gcc  -o sigdcp ${GLBT_LIB_PATH}/glb_tools_parser.o ${GLBT_LIB_PATH}/glb_tools_header.o ${GLBT_LIB_PATH}/glb_tools_eightfold.o ../customchis/customChis.o -lglobes -lgsl -lgslcblas -lm -L${GLBT_LIB_PATH}/lib -L${INSTALLATION}/lib sigdcp.c

