sys(#err_nue_sig)<
  @error = ERR_NUE_SIG
>

sys(#err_nue_sigbar)<
  @error = ERR_NUE_SIGBAR
>

sys(#err_numu_sig)<
  @error = ERR_NUMU_SIG
>

sys(#err_numu_sigbar)<
  @error = ERR_NUMU_SIGBAR
>

sys(#err_numu_bg)<
  @error = ERR_NUMU_BG
>

sys(#err_nue_bg)<
  @error = ERR_NUE_BG
>

sys(#err_nutau_bg)<
  @error = ERR_NUTAU_BG
>

sys(#err_nue_bgbar)<
  @error = ERR_NUE_BGBAR
>

sys(#err_nc_bgdis)<
  @error = ERR_NC_BGDIS
>
